### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by IzzySoft** [MistralMireille/MHTML-Viewer#1]
Looks like all your APKs identify as

    package: name='com.example.webpdf' versionCode='1' versionName='1.0'

i.e. `versionCode` was never increased (which Android needs to tell versions apart), and `versionName` never adjusted (which humans use to tell versions apart). Could you please [take care for this](https://github.com/MistralMireille/MHTML-Viewer/blob/master/app/build.gradle#L9) with the latest and future releases? Given there were 3 releases with the latest being tagged `v0.9.5`, may I suggest to make that last one

```gradle
        versionCode 3
        versionName "0.9.5"
```

(and future ones accordingly)? Thanks in advance!

**Comment by MistralMireille** [comment]
I updated the last release, and I'll keep this in mind going forward. Thank you for letting me know.

**Comment by IzzySoft** [comment]
Great, thanks! Added your app to my repo then – will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.example.webpdf) around 7 pm UTC with the next sync. Would be great if you could add a "dedicated icon" to replace the default Andy :wink: And be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme :smiley:
