### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [MistralMireille/MHTML-Viewer#2]
Hi please support the Android 13 Themed Icons feature.

![Screenshot_2023-03-01-03-57-27-901_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/222014029-803073f9-7b58-4d7c-a394-6fea8a6f00c3.jpg)

**Comment by MistralMireille** [comment]
I updated the last release with an icon that supports themed icons. It works in the emulator but this is the first change where I can't actually check if it works on my phone, so I'm a bit anxious. If anything doesn't work right, let me know and I'll reopen the issue.

**Comment by xmha97** [comment]
Thanks 🙏
It's working fine.

![Screenshot_2023-03-03-19-38-19-401_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/222769628-5c940eca-9326-47f6-a138-c9e1fa6ec0bc.jpg)

But I suggest you create a new release.
